### ISSUE TITLE
Extension Install fails with Application Event Message

### ISSUE THREAD

**Issue by jratclif** [colindembovsky/cols-agent-tasks#61]
I downloaded the package for Visual Studio Market Place and installed it in TFS 2015 Update 3.

The install did not throw any errors.
No Steps were added.
Found this in the Application Event Log
-----------

TF53010: The following error has occurred in a Team Foundation component or extension:
Date (UTC): 6/5/2017 5:43:13 PM
Machine: IVPTFS
Application Domain: /LM/W3SVC/2/ROOT/tfs-1-131411579076200198
Assembly: Microsoft.TeamFoundation.Framework.Server, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a; v4.0.30319
Service Host: c0b051f3-21ce-48aa-af34-fcf7aeaed433 (TEAM FOUNDATION)
Process Details:
  Process Name: w3wp
  Process Id: 1344
  Thread Id: 4336
  Account name: TQL\TFSAdmin

Detailed Message: TF30065: An unhandled exception occurred.

Web Request Details
    Url: http://ivptfs:8080/tfs/_gallery/items/colinsalmcorner.colinsalmcorner-buildtasks?targetId=7cad50fc-953d-424a-8ab8-640dcfb0a0b4 [method: GET]
    User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/6.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)
    Headers: not available
    Path: /tfs/_gallery/items/colinsalmcorner.colinsalmcorner-buildtasks
    Local Request: True
    Host Address: fe80::ed94:b859:e9b:fa94%12
    User: TQL\TFSAdmin [authentication type: NTLM]

Exception Message: This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet. (type InvalidOperationException)
Exception Stack Trace:    at System.Web.Mvc.JsonResult.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar)
   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by colindembovsky** [comment]
Hi @jratclif - hmm, this seems like an install issue, not an extension issue, if that makes sense. I know that the install "succeeds" but really fails because of minimum agent versions etc., especially with TFS 2015.3.

I think the best way to debug this is for you to:
1. Change the vsix file to .zip
2. Unzip
3. Run `tfx build tasks upload` and upload the task(s) - that would at least produce error messages that we could see.
